### ISSUE TITLE
Please tag a 2.0.0 release

### ISSUE THREAD

**Issue by gfa** [bodgit/puppet-bodgitlib#10]
Hi

I'm pulling my  modules from github instead of puppet forge using git tags, there is a release 2.0.0 in puppeforge but not the corresponding tag here in github.
Could you please tag 2.0.0 in the repo?

thanks!

**Comment by bodgit** [comment]
You're right, not sure how that got missed.

**Comment by bodgit** [comment]
I'd made the tag, but not pushed it. It's there now.
