### ISSUE TITLE
LDAP filter validator issue

### ISSUE THREAD

**Issue by coreone** [bodgit/puppet-bodgitlib#8]
Hello,

I have an LDAP filter I'm trying to get working and the `validate_ldap_filter` function keeps flagging the filter as invalid.  I have used this filter for years, so I know it is correct, so I guess the question is, why is the regex being used in this validator function marking it as invalid.  The filter is as follows:

```
(&(sAMAccountName=%u)(!(memberOf=cn=groupname,ou=User Security Groups,ou=Users,dc=my,dc=example,dc=com)))
```

I imagine it has something to do with the syntax of **memberOf** matches that have a lot of extra *=* in there.

Is there any way to update the regex so that this will validate as correct?  If not, I'm going to have to figure out a way round this validator function in the puppet-sasl module.

Thanks!

**Comment by bodgit** [comment]
More test input for these functions is always useful :wink: I'll take a look

**Comment by coreone** [comment]
I tested this a little further, and the problem is definitely after `memberOf`.  If I quote everything after the equal sign, the `validate_ldap_filter` function succeeds.

```
(&(sAMAccountName=%u)(!(memberOf="cn=groupname,ou=User Security Groups,ou=Users,dc=my,dc=example,dc=com")))
```

However, this filter does not work in *saslauthd* because the quotes, although they make the filter valid as far as `validate_ldap_filter` is concerned, the quotes render the filter useless as it cannot match against `memberOf` any longer.  If I put a space between the `memberOf=` and the rest of the group DN, the validation function still fails, but that filter works in saslauthd.
```
(&(sAMAccountName=%u)(!(memberOf= cn=groupname,ou=User Security Groups,ou=Users,dc=my,dc=example,dc=com)))
```
Not sure if that makes it easier to fix the regex or not, but at least it narrows down the problem.

**Comment by bodgit** [comment]
So this was in part down to the older LDAP RFC's and the newer ones which obsoleted them. RFC 2254 was the original which defined the value side of the search filter as characters not containing `,` and `=` amongst others which meant it wouldn't pass your test case. That's what the regex was written in terms of. RFC 4515 updates this syntax and is much clearer on what characters are forbidden, or rather at least what should be escaped as their hex equivalent. I've updated the test cases with your example along a few that have appeared in RFC 4515 and they now all pass.

I've uploaded a new v1.5.1 version of the module to the forge so you should be able to update to that. Thanks again for the bug report!
